name: ci
on:
  push:
    branches:
      - main
      - master # Comme ça, peu importe le nom de ta branche, ça marche

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps: deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: mkdocs build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site # Le dossier créé par mkdocs
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
